config/routes.rb
Rails.application.routes.draw do
  resources :games do 
    resources :reviews, only: [:new, :show]
  end
  resources :reviews
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'reviews#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :reviews
  has_many :users, through: :reviews

  validates :title, presence: true, uniqueness: true
  validates :title, length: { maximum: 35 }
  validate :is_title_case

  def is_title_case
    if title.split.any?{|w|w[0].upcase != w[0]}
      errors.add(:title, "must be in title case")
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :rating, presence: true
  validates :rating, :inclusion => { :in => 1..5, :message => " should be between 1 to 5" }
  validates :content, presence: true, length: { maximum: 600 }

  # sort by good rating and bad rating or filter <= 3 = bad rating, >= 3 = good rating

  def posted
    created_at.in_time_zone("America/Chicago").strftime("Posted: %b %e, %l:%M %p")
  end

  def last_updated
    updated_at.in_time_zone("America/Chicago").strftime("Updated at: %b %e, %l:%M %p")
  end

  def self.most_recent
    order(created_at: :desc)
  end

  def self.oldest
    order(created_at: :asc)
  end

  def self.high_rating
    order(rating: :desc)
  end

  def self.low_rating
    order(rating: :asc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :games, through: :reviews 

  validates :username, uniqueness: true, if: :username
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: [:google_oauth2]
         def self.from_google(uid:, email:, full_name:, avatar_url:)
          if user = User.find_by(email: email)
            user.update(uid: uid, full_name: full_name, avatar_url: avatar_url) unless user.uid.present?
            user
          else
            User.create(
              email: email,
              uid: uid,
              full_name: full_name,
              avatar_url: avatar_url,
              password: SecureRandom.hex
            )
          end
        end

        def display_name
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    # rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
    # def not_found
    #   flash[:error] = "Page not found"
    #   redirect_to root_path
    # end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_game, only: [:show]

    def index
        @games = Game.all
    end

    def show
    end

    def new
        @game = Game.new
    end

    def create
        @game = Game.new(game_params)
        if @game.save
            redirect_to game_path(@game)
        else
            render :new
        end
    end

private

    def set_game
        @game = Game.find(params[:id])
    end

    def game_params
        params.require(:game).permit(:title)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :review_owner, only: [:edit, :update, :destroy]

  def index
    @game = Game.find_by_id(params[:game_id])
    if @game
      @reviews = @game.reviews
    else
      @reviews = Review.all
    end
    sort_options 
  end  

  def show
  end 

  def new
    @game = Game.find_by_id(params[:game_id])
    if @game
      @review = @game.reviews.build
    else
    @review = Review.new
    end
  end

  def create 
    @review = current_user.reviews.build(review_params)
    if @review.save 
      redirect_to review_path(@review)
    else 
      render :new
    end
  end   

  def edit
  end

  def update 
    if @review.update(review_params)
      flash[:success] = "Review updated"
      redirect_to review_path(@review)
    else 
      render :edit
    end
  end   

  def destroy
    @review.destroy
    flash[:success] = "Review deleted"
    redirect_to reviews_path
  end

private

  def set_review
    @review = Review.find(params[:id])
  end

  def sort_options
    if params[:sort] == "most_recent"
      @reviews = @reviews.most_recent
    elsif params[:sort] == "oldest"
      @reviews = @reviews.oldest
    end
  end

  def review_params
    params.require(:review).permit(:game_id, :user_id, :rating, :content, :created_at, :updated_at)
  end
  
  def review_owner
  unless @review.user_id == current_user.id
    flash[:error] = 'Access denied'
    redirect_to reviews_path
   end
  end  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      user = User.from_google(from_google_params)
      
      if user.persisted?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect user, event: :authentication
      else
        flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
        redirect_to new_user_session_path
      end
    end
  
    protected
  
    def after_omniauth_failure_path_for(_scope)
      new_user_session_path
    end
  
    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end
  
    private
  
    def from_google_params
    
      @from_google_params ||= {
        uid: auth.uid,
        email: auth.info.email,
        full_name: auth.info.name,
        avatar_url: auth.info.image
      }
    end
  
    def auth
      @auth ||= request.env['omniauth.auth']
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
    def show_errors_for(obj)
        render partial: 'shared/errors', locals: {obj: obj} 
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/games/index.html.erb
<br>

<div class="addgame">
    <%= link_to 'Add Game', new_game_path, class: "btn btn-primary" %>
</div>
    <h1>Games</h1>
<p> </p>
<ul>
 <% @games.each do |game| %>
    <li>
        <%= link_to game.title, game_path(game) %> 

        <% unless game.reviews.empty? %>
        <%= pluralize game.reviews.count, "review" %>
        <% end %>
    </li>
 <% end %>
</ul>

app/views/games/new.html.erb
<br>
<h1>Create a new game</h1>
<%= show_errors_for(@game)%>

<br>
<div class="form-group">
    <%= form_for @game do |f| %>
        <%= f.text_field :title, placeholder: "Add title", class: "form-control" %>
        <br>
        <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/games/show.html.erb
<h1><%= @game.title %></h1><br>
    <% if @game.reviews.empty? %>
        Be the first to make a <u><%= link_to 'review', new_game_review_path(@game) %></u>
    <% else %>
<ul>
<% @game.reviews.each do |review| %>
<li>
    <%= link_to review.user.username, game_review_path(@game, review) %>
</li>
</ul>
<% end %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GRZ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render partial: 'shared/navbar' %>
  
  <body>
  <div class="wrapper">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>
    
    <footer class="branding">
      <small>&copy; 2020 <strong>GRZ</strong></small>
      <a href="https://dev.to/tyraino">
        <img src="https://d2fltix0v2e0sb.cloudfront.net/dev-badge.svg" alt="royalterminal_'s DEV Profile" height="30" width="30">
      </a>
    </footer>
  </body>
  </div>
</html>

app/views/reviews/_form.html.erb
<%= show_errors_for(review)%>

    <%= form_for review do |f| %>
      <%= f.collection_select :game_id, Game.all, :id, :title, include_blank: "Choose a game" %>
    <p> </p>
<div class="form-group">
    <%= f.text_field :rating, placeholder: "Rating (1-5)", class: "form-control" %>
    <p> </p>
            <div class="textarea">
          <%= f.text_area :content, class: "form-control", placeholder: "Write your review..." %>
          </div>
        </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
 <br>
<%= f.submit class: "btn btn-primary"  %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= render partial: 'form', locals: { review: @review } %>

app/views/reviews/index.html.erb
<br>
<h1>Reviews</h1>

<%= form_tag(reviews_path, method: 'get') do %>
<label for="sort">Sort by</label>
  <select name="sort">
    <option <%= 'selected' if params[:sort] == '' %> value="">None</option>
    <option <%= 'selected' if params[:sort] == 'most_recent' %> value="most_recent">Most Recent</option>
    <option <%= 'selected' if params[:sort] == 'oldest' %> value="oldest">Oldest</option>
  </select>
<%= submit_tag "Sort Results", class: "btn btn-outline-primary btn-sm"%>
<% end %>
<br>
<%= link_to 'Create a Review', new_review_path, class: "btn btn-primary" %>
<br>
<br>
<% if @reviews.empty?%>
  Be the first to make a review!
<% else %>
<p> </p>
<ul>
 <% @reviews.each do |review| %>
    <li>
        <%= link_to review.game.title, review_path(review) %>
        ・ <%=review.user.username || review.user.full_name%>
    </li>
 <% end %>
 <% end %>
</ul>

app/views/reviews/new.html.erb
<br>
<h1>Create a Review</h1>
<%= render partial: 'form', locals: { review: @review } %>

app/views/reviews/show.html.erb
<h1><%= @review.game.title %> Review<br></h1>

<h1>By <%= @review.user.username || @review.user.full_name %></h1>
<h3><%= @review.posted %> ・ <%= @review.last_updated %> </h3>

<h4> Rating: <%= @review.rating %><br></h4>
<%= @review.content %>

<p> </p>

<% if user_signed_in? && current_user.id == @review.user_id %>
    <%= link_to 'Edit review', edit_review_path(@review), class: "btn btn-primary" %>

    <%= form_tag(review_path(@review), method: :delete, style: 'display: inline-block;') do %>
    <%= submit_tag "Delete review", class: "btn btn-primary", data: { confirm: "Are you sure you want to delete this review?"}%>
    <% end %>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase %> from being saved:</h2>
 
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">GRZ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
         <%= link_to 'Reviews', reviews_path %>
      </li>
      <li class="nav-item">  
        <%= link_to 'Games', games_path %>
      </li>
      <li class="nav-item">
      
      </li>
      
    </ul>
    
      <% if user_signed_in? %>
    <%= form_tag(destroy_user_session_path, method: :delete, style: 'display: inline-block;') do %>
    <%= submit_tag "Sign Out", class: "btn btn-outline-primary" %>
   <% end %>
  <% else %>

    <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-outline-primary" %>
    <%= link_to 'Sign In', new_user_session_path, class: "btn btn-outline-primary" %>
   <% end %>
  
  </div>
</nav>